// export type Sudoku = {
//     GameCombo: []
// }

// type GameCombo = {
//     B1: string;
//     B2: string;
//     B3: string;
//     B4: string;
//     B5: string;
//     B6: string;
//     B7: string;
//     B8: string;
//     B9: string;
//     B10: string;
//     B11: string;
//     B12: string;
//     B13: string;
//     B14: string;
//     B15: string;
//     B16: string;
//     B17: string;
//     B18: string;
//     B19: string;
//     B20: string;
//     B21: string;
//     B22: string;
//     B23: string;
//     B24: string;
//     B25: string;
//     B26: string;
//     B27: string;
//     B28: string;
//     B29: string;
//     B30: string;
//     B31: string;
//     B32: string;
//     B33: string;
//     B34: string;
//     B35: string;
//     B36: string;
//     B37: string;
//     B38: string;
//     B39: string;
//     B40: string;
//     B41: string;
//     B42: string;
//     B43: string;
//     B44: string;
//     B45: string;
//     B46: string;
//     B47: string;
//     B48: string;
//     B49: string;
//     B50: string;
//     B51: string;
//     B52: string;
//     B53: string;
//     B54: string;
//     B55: string;
//     B56: string;
//     B57: string;
//     B58: string;
//     B59: string;
//     B60: string;
//     B61: string;
//     B62: string;
//     B63: string;
//     B64: string;
//     B65: string;
//     B66: string;
//     B67: string;
//     B68: string;
//     B69: string;
//     B70: string;
//     B71: string;
//     B72: string;
//     B73: string;
//     B74: string;
//     B75: string;
//     B76: string;
//     B77: string;
//     B78: string;
//     B79: string;
//     B80: string;
//     B81: string;
// }

// export const easyMode: Sudoku = {
//     B1: "6",
//     B2: "7",
//     B3: "2",
//     B4: "8",
//     B5: "3",
//     B6: "1",
//     B7: "5",
//     B8: "4",
//     B9: "9",
//     B10: "5",
//     B11: "3",
//     B12: "1",
//     B13: "";
//     B14: string;
//     B15: string;
//     B16: string;
//     B17: string;
//     B18: string;
//     B19: string;
//     B20: string;
//     B21: string;
//     B22: string;
//     B23: string;
//     B24: string;
//     B25: string;
//     B26: string;
//     B27: string;
//     B28: string;
//     B29: string;
//     B30: string;
//     B31: string;
//     B32: string;
//     B33: string;
//     B34: string;
//     B35: string;
//     B36: string;
//     B37: string;
//     B38: string;
//     B39: string;
//     B40: string;
//     B41: string;
//     B42: string;
//     B43: string;
//     B44: string;
//     B45: string;
//     B46: string;
//     B47: string;
//     B48: string;
//     B49: string;
//     B50: string;
//     B51: string;
//     B52: string;
//     B53: string;
//     B54: string;
//     B55: string;
//     B56: string;
//     B57: string;
//     B58: string;
//     B59: string;
//     B60: string;
//     B61: string;
//     B62: string;
//     B63: string;
//     B64: string;
//     B65: string;
//     B66: string;
//     B67: string;
//     B68: string;
//     B69: string;
//     B70: string;
//     B71: string;
//     B72: string;
//     B73: string;
//     B74: string;
//     B75: string;
//     B76: string;
//     B77: string;
//     B78: string;
//     B79: string;
//     B80: string;
//     B81: string;
// }
